### ISSUE TITLE
hr() problem

### ISSUE THREAD

**Issue by gmosx** [pointfreeco/swift-web#126]
Currently if I use `hr()` instead of `hr([])` I get this strange error:

```
error: contextual type '([Attribute<Element.Body>], [Node])' cannot be used 
with array literal body([
```

Perhaps `hr()` should be supported as a shorthand?

**Comment by mbrandonw** [comment]
@gmosx sorry late to this. Yeah that's a good point, we should either have an overload that takes no arguments, or use an empty array. we'll consider this soon, thanks!

**Comment by stephencelis** [comment]
Think `hr` is a value now in swift-html.
