### ISSUE TITLE
Possible alternative to scoping

### ISSUE THREAD

**Issue by mbrandonw** [pointfreeco/swift-web#13]
idea from Cornett:

```swift
// before
let stylesheet = input % (
  baseInputStyle
    <> .pseudo(.focus) & (
      color(red)
  )
)

// after
let stylesheet = input % (
  baseInputStyle
    <&> .pseudo(.focus) % (
      color(red)
  )
)
```

**Comment by stephencelis** [comment]
Can you edit the above with a "before" example?

**Comment by mbrandonw** [comment]
@stephencelis done! not sure if it's possible, but fun to think about ways to improve the syntax

**Comment by stephencelis** [comment]
I think we'll have lots of new CSS ideas whenever we revisit the topic :smile: For now: 🚪
