### ISSUE TITLE
Inconsistency with Swift's standard naming conventions

### ISSUE THREAD

**Issue by gmosx** [pointfreeco/swift-web#132]
I have the feeling that, in the spirit of Swift's standard library (and Foundation) it should be:

```
HTML
CSSSelector
HTTPPipeline
etc..
```

instead of

```
Html
CssSelector
HttpPipeline
etc..
```

examples from Stdlib/Foundation:

```
String.UTF8View
URLSession
etc...
```

**Comment by stephencelis** [comment]
Going to close this since it's a bit stale. We've preferred the unconventional naming since it's an easy rule to follow, but perhaps we should revisit the discussion sometime.
