### ISSUE TITLE
failing test testCookieOptions

### ISSUE THREAD

**Issue by weissi** [pointfreeco/swift-web#135]
## problem
Just ran the swift-web tests and they fail.

```
Test Case '-[HttpPipelineTests.HttpPipelineTests testCookieOptions]' started.
/private/tmp/.nio-release-tools_bcOmLA/swift-web/Tests/HttpPipelineTests/HttpPipelineTests.swift:79: error: -[HttpPipelineTests.HttpPipelineTests testCookieOptions] : failed - Diff: …

@@ −11,9 +11,9 @@
   Content-Length: 19
   Content-Type: text/html; charset=utf-8
   Set-Cookie: foo=bar; Domain=www.pointfree.co
   Set-Cookie: foo=bar; Domain=www.pointfree.co; HttpOnly; Secure
−  Set-Cookie: foo=bar; Expires=Fri, 13 Feb 2009 23:31:30 GMT
+  Set-Cookie: foo=bar; Expires=Fri, 13 Feb 2009 11:31:30 pm GMT
   Set-Cookie: foo=bar; HttpOnly
   Set-Cookie: foo=bar; Max-Age=3600
   Set-Cookie: foo=bar; Path=/path/to/some/where
   Set-Cookie: foo=bar; SameSite=Lax
```

## guess about what's causing this

It might be a US vs UK locale issue. This is my locale

```
$ locale
LANG="en_GB.UTF-8"
LC_COLLATE="en_GB.UTF-8"
LC_CTYPE="en_GB.UTF-8"
LC_MESSAGES="en_GB.UTF-8"
LC_MONETARY="en_GB.UTF-8"
LC_NUMERIC="en_GB.UTF-8"
LC_TIME="en_GB.UTF-8"
LC_ALL=
```

## environment

- swift-web commit: https://github.com/pointfreeco/swift-web/commit/702ddc3f14adfeaa98befae5556fda97b45425aa
- swift version: 4.2 pre-release
- platform: macOS

**Comment by stephencelis** [comment]
Hi @weissi! Thanks for the report! Any chance you can check out [this branch](https://github.com/pointfreeco/swift-web/pull/136) and see if that fixes things? I tried hard-coding `en_GB` to get a failing test but everything still passed, so I wonder if something more subtle is happening here.

**Comment by weissi** [comment]
@stephencelis , thanks for the super quick turnaround, that fixes it 👍
