### ISSUE TITLE
HttpPipelineTests.testCookies and HttpPipelineTests.testCookieOptions fail on 4.1 on Linux with ICU >= version 59

### ISSUE THREAD

**Issue by weissi** [pointfreeco/swift-web#139]
sorry me again, this time `"GMT"` vs `"UTC"`

```
Test Case 'HttpPipelineTests.testCookies' started at 2018-05-30 12:26:44.979
swift-web/Tests/HttpPipelineTests/HttpPipelineTests.swift:60: error: HttpPipelineTests.testCookies : failed - Diff: …

@@ −10,9 +10,9 @@
   Status 200 OK
   Content-Length: 19
   Content-Type: text/html; charset=utf-8
   Set-Cookie: lang=es
−  Set-Cookie: test=; Expires=Thu, 1 Jan 1970 00:00:00 GMT; Max-Age=0
+  Set-Cookie: test=; Expires=Thu, 1 Jan 1970 00:00:00 UTC; Max-Age=0
   Set-Cookie: user_id=123456
 
   <p>Hello, world</p>
 
Test Case 'HttpPipelineTests.testCookies' failed (0.007 seconds)
Test Case 'HttpPipelineTests.testCookieOptions' started at 2018-05-30 12:26:44.987
swift-web/Tests/HttpPipelineTests/HttpPipelineTests.swift:79: error: HttpPipelineTests.testCookieOptions : failed - Diff: …

@@ −11,9 +11,9 @@
   Content-Length: 19
   Content-Type: text/html; charset=utf-8
   Set-Cookie: foo=bar; Domain=www.pointfree.co
   Set-Cookie: foo=bar; Domain=www.pointfree.co; HttpOnly; Secure
−  Set-Cookie: foo=bar; Expires=Fri, 13 Feb 2009 23:31:30 GMT
+  Set-Cookie: foo=bar; Expires=Fri, 13 Feb 2009 23:31:30 UTC
   Set-Cookie: foo=bar; HttpOnly
   Set-Cookie: foo=bar; Max-Age=3600
   Set-Cookie: foo=bar; Path=/path/to/some/where
   Set-Cookie: foo=bar; SameSite=Lax
Test Case 'HttpPipelineTests.testCookieOptions' failed (0.005 seconds)
```

environment:

```
root@34977f49e9d9:/Users/johannes# swift -version
Swift version 4.1 (swift-4.1-RELEASE)
Target: x86_64-unknown-linux-gnu
root@34977f49e9d9:/Users/johannes# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
root@34977f49e9d9:/Users/johannes# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
```

maybe that's a corelibs-foundation bug actually?

**Comment by mbrandonw** [comment]
Hey @weissi, thanks for all useful test failures!

This one we are having some trouble reproducing. If we run our `make linux-test` command we don't get any failures. That spins up a docker container (with Ubuntu 16.04) with the same locale you are showing above, yet we don't get any failures.

The only differences I see in our setup is Ubuntu 14.04 vs 16.04. Could you either try running our make command to see if it works, or share your docker file set up?

Thanks!

**Comment by mbrandonw** [comment]
Also, Travis CI runs tests in Ubuntu 14.04:

```
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

and tests pass there... so even stranger.

**Comment by weissi** [comment]
@mbrandonw hmm, odd, so I have this

```
root@d444396341a6:/tmp/swift-web# date
Wed May 30 13:39:47 UTC 2018
root@d444396341a6:/tmp/swift-web# cat /etc/timezone 
Etc/UTC
```

is that odd timezone maybe the prob?

**Comment by mbrandonw** [comment]
Same for me:

```
root@53eadcc26989:/# date
Wed May 30 13:47:34 UTC 2018

root@53eadcc26989:/# cat /etc/timezone
Etc/UTC

root@53eadcc26989:/# locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=

root@53eadcc26989:/# swift --version
Swift version 4.1 (swift-4.1-RELEASE)
Target: x86_64-unknown-linux-gnu
```

**Comment by weissi** [comment]
@mbrandonw ok, I think I know why: We're using ICU version 62 here but the old Ubuntus are usually shipping with 52 or 55. Note that you're asking for `TimeZone(abbreviation: "UTC")` but then testing that it's `"GMT"`. So I think the old ICU versions had a bug where they used "GMT" even though you asked for "UTC"... Not that there's [a subtle difference between UTC and GMT](https://www.timeanddate.com/time/gmt-utc-time.html), UTC not actually being a time zone.

When I change the [two](https://github.com/pointfreeco/swift-web/blob/096b018ad31d568a055ba5f0376df0e41aca8685/Sources/HttpPipeline/Response.swift#L146) [occurances](https://github.com/pointfreeco/swift-web/blob/de9704da6834d65f9e8a7b54b69147dc577cf902/Sources/UrlFormEncoding/UrlFormDecoder.swift#L652) of UTC to GMT, the tests pass everywhere so I think that'd be a good idea :)

**Comment by weissi** [comment]
@stephencelis / @mbrandonw yes, that's a libICU change that was introduced in [version 59](http://site.icu-project.org/download/59)

> GMT and UTC are no longer unified, and CLDR provides distinct UTC display names, avoiding confusion with standard (winter) time in Britain.

so this test will fail on any Linux with ICU >= 59.

**Comment by mbrandonw** [comment]
Wow, nice find! I've got a PR up here: https://github.com/pointfreeco/swift-web/pull/140.

**Comment by mbrandonw** [comment]
Ok it's merged! hope that's the last of the this cookie bug 🤞

**Comment by weissi** [comment]
awesome, ta, kicking the next test runs off :)
