### ISSUE TITLE
map

### ISSUE THREAD

**Issue by emilwojtaszek** [pointfreeco/swift-web#191]
@stephencelis is there a better/nicer way to perform this kind of operation:

```swift
public func mapMiddleware<A, B>(
  _ f: @escaping (A) -> B
  )
  -> (@escaping Middleware<StatusLineOpen, ResponseEnded, B, Data>)
  -> Middleware<StatusLineOpen, ResponseEnded, A, Data> {

    return { middleware in
      return { $0.map(f) |> middleware }
    }
}
```

**Comment by stephencelis** [comment]
Hey @emilwojtaszek! Sorry for the delay. We don't monitor this repo's issues/PRs as closely as some of our other open source. An operation we find helpful is `filterMap`, which we use all over the @pointfreeco code base: https://github.com/pointfreeco/pointfreeco/search?utf8=✓&q=filterMap&type=

It allows for a failable transformation into `nil` with a failover middleware.

@mbrandonw and I are hoping to explore some ergonomic improvements to the HTTP pipeline soon!
